Checking MLflow version...
mlflow, version 2.13.0

Running preprocessing...

Training model...

Please run the following command in a separate terminal to keep the tracking server running:

mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts

Running hyperparameter optimization...

  0%|          | 0/15 [00:00<?, ?trial/s, best loss=?]
  7%|▋         | 1/15 [00:07<01:51,  7.96s/trial, best loss: 5.370086069268862]
 13%|█▎        | 2/15 [00:08<00:45,  3.49s/trial, best loss: 5.370086069268862]
 20%|██        | 3/15 [00:08<00:25,  2.14s/trial, best loss: 5.370086069268862]
 27%|██▋       | 4/15 [00:14<00:37,  3.42s/trial, best loss: 5.357490752366866]
 33%|███▎      | 5/15 [00:16<00:31,  3.15s/trial, best loss: 5.357490752366866]
 40%|████      | 6/15 [00:26<00:47,  5.22s/trial, best loss: 5.354695072530291]
 47%|████▋     | 7/15 [00:35<00:51,  6.47s/trial, best loss: 5.354695072530291]
 53%|█████▎    | 8/15 [00:36<00:32,  4.71s/trial, best loss: 5.354695072530291]
 60%|██████    | 9/15 [00:41<00:29,  4.99s/trial, best loss: 5.354695072530291]
 67%|██████▋   | 10/15 [00:46<00:24,  4.90s/trial, best loss: 5.354695072530291]
 73%|███████▎  | 11/15 [00:49<00:17,  4.48s/trial, best loss: 5.335419588556921]
 80%|████████  | 12/15 [00:52<00:11,  3.98s/trial, best loss: 5.335419588556921]
 87%|████████▋ | 13/15 [00:53<00:06,  3.08s/trial, best loss: 5.335419588556921]
 93%|█████████▎| 14/15 [00:57<00:03,  3.15s/trial, best loss: 5.335419588556921]
100%|██████████| 15/15 [01:02<00:00,  3.75s/trial, best loss: 5.335419588556921]
100%|██████████| 15/15 [01:02<00:00,  4.15s/trial, best loss: 5.335419588556921]

Registering best model...

Error running command: ['/home/codespace/.python/current/bin/python', 'register_model.py']
Traceback (most recent call last):
  File "/workspaces/mlops-zoomcamp-May2024/02-Homework2/register_model.py", line 80, in <module>
    run_register_model()
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspaces/mlops-zoomcamp-May2024/02-Homework2/register_model.py", line 76, in run_register_model
    mlflow.register_model( ... )
TypeError: register_model() missing 1 required positional argument: 'name'

